### ISSUE TITLE
HW2 ready for grading

### ISSUE THREAD

**Issue by massemassiv** [massemassiv/su-mt4007#2]

**Comment by OliviaRislund** [comment]
The report has answered all the questions, and the code seems to provide the correct answers. The document has a clean layout and contains only the necessities to address the given questions. While reading the report, I thought the subject chosen for the last question was excellent, and I appreciated how the person resolved any potential confusion in the scatterplot by creating another plot that was easier to understand. There wasn’t really anything confusing, but if I had to point something out, it would be to maybe include in the title that this was Homework 2. However, this is not particularly important.

**Comment by LeoLevenius** [comment]
# $${\color{green}\text{Godkänt.}}$$

**Comment by AlvinaLind** [comment]
Yes, I think the report addresses all the required tasks and questions for analyzing the datasets. I really like how the scatterplot and smoothed line graph for the stroke data clearly highlight the relationship between age, gender, and stroke probability. I can't find anything specific that feels unclear to me.
